nifty50_stocks = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "HINDUNILVR.NS",
    "ICICIBANK.NS", "INFY.NS", "KOTAKBANK.NS", "ITC.NS",
    "HDFC.NS", "LT.NS", "BAJFINANCE.NS", "ASIANPAINT.NS",
    "AXISBANK.NS", "TITAN.NS", "MARUTI.NS", "SBIN.NS",
    "HCLTECH.NS", "TECHM.NS", "ONGC.NS", "NESTLEIND.NS",
    "BAJAJFINSV.NS", "NTPC.NS", "POWERGRID.NS", "SUNPHARMA.NS",
    "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "DRREDDY.NS", "ULTRACEMCO.NS",
    "M&M.NS", "COALINDIA.NS", "BRITANNIA.NS", "JSWSTEEL.NS",
    "GRASIM.NS", "SHREECEM.NS", "ADANIPORTS.NS", "DIVISLAB.NS",
    "CIPLA.NS", "EICHERMOT.NS", "TATAMOTORS.NS", "IOC.NS",
    "HINDALCO.NS", "TATASTEEL.NS", "UPL.NS", "INDUSINDBK.NS",
    "VEDL.NS", "WIPRO.NS", "SBILIFE.NS", "BPCL.NS"
]